- debugger.lua
Not sure why, but the escapes don't seem to work on Mac. Changed it to string.char instead.
> Fixed color output

- debugger.lua
https://github.com/hoelzro/lua-linenoise now supports colored prompts thanks to [this commit](https://github.com/hoelzro/lua-linenoise/commit/aa5d70355171e32361771c336adee9ca3e794fcc), so we can remove the code that strips out ANSI characters.
> enable ansi prompt for linenoise

- debugger-lua-scm-1.rockspec
Earlier, this pointed to an HTML file.
> Fix rockspec to point to raw lua file

- debugger.lua
Before this commit, `dbg.call` only returns `true` or ` false`.
For feature parity with `pcall`, it must pass the entire tuple back to its caller.
```lua
local ok, a, b, c = dbg.call(function()
return 1, 2, 3
end)
```
> improve dbg.call parity with pcall

- debugger.lua
The print command should print all return values, even if nil precedes the value(s).
> fix: use table.maxn in cmd_print

- debugger.lua
Now, the print command works with:
```lua
-- ordinary tuples
p 1, 2, 3
-- sparse tuples
p 1, nil, 2
-- trailing nils
p 1, 2, nil
-- just nil
p nil
-- nothing
p (function() end)()
```
Fixes ee4da2ed66b3eeb63809e98cd0991759f2190c5e
> fix: use table.pack instead of table.maxn

- debugger.lua
- `step` and `next` now return to the bottom frame
Previously, if I used `up` and then `step` or `next`, the inspected frame would remain the same. With this commit, the inspected frame is reset to the bottom frame (aka the active frame).
- `finish` now works relative to the inspected frame
Previously, if I used `up` and then `finish`, the inspected frame would remain the same and only the bottom frame would be stepped out of. With this commit, the `finish` command will step up the stack until the inspected frame has been exited.
> reset inspected frame on step/next/finish

- debugger.lua
While looking for the next inspectable frame, the `down` command accidentally went past the bottom of the stack (known as `stack_top` in the code).
> fix: cmd_down past stack_top

- debugger.lua
The `what` property equals "main" when using `dbg()` within `foo.lua` where `lua foo.lua` was used, for example.
> fix: assume what="main" frames have a file

- debugger.lua
Using the # operator on varargs returns zero when the first vararg equals nil.
> fix: varargs binding

- debugger.lua
Previously, an `error` call would prevent calls to `repl` because
the stack offset wasn't being reset properly.
This commit fixes that by setting the `offset` to -1 when
an `error` call is encountered, which allows `hook_factory`
instances to call `repl` on the next encountered Lua line.
Also, the `repl` function is now called *only* when a "line"
event is for a Lua function. This means the repl is never used
to inspect a C function (which is pointless).
> fix: account for `error` calls in hook_factory

- README.md
- debugger.lua
I squashed the commits by @churay that add a where command that print the lines of code surrounding the current breakpoint.
```lua
debugger.lua> w
58	             stream.headers = headers
59	           else
60	             return stream:shutdown(), app:onerror(err)
61	           end
62	           dbg()
63	=>         local res = setmetatable({
64	             headers = http_headers.new()
65	           }, res_mt)
66	           local _list_0 = app.pipes
67	           for _index_0 = 1, #_list_0 do
68	             local _continue_0 = false
debugger.lua> w 7
56	           local headers, err = stream:get_headers()
57	           if headers then
58	             stream.headers = headers
59	           else
60	             return stream:shutdown(), app:onerror(err)
61	           end
62 …
```
> feat: add where command

- README.md
IMO it's easier to parse the readme if the code is actually highlighted. Feel free to ignore this if that's not desired.
> Add Fenced Code Blocks to Enable Lua Syntax Highlighting

- debugger.lua
This PR is three small bugfixes for corner cases:
- Fix behavior of assert() to return value like Lua's assert
- Fix internal error when concat'ing table errors
- Fix prompt display in Busybox
Thank you for the useful library!
> Bug fixes for various corner cases

- debugger.lua
This makes the library usable with [luvit](https://github.com/luvit/luvit) runtime, however the tests wont run correctly because of the change in behaviour of 'require' (and it's output).
The library does work as expected as far as I've tested it even tho the tests mostly fail.
eg:
`expected: test.lua:12 in upvalue 'func2'
got     : E:\Projects\Lua\debugger.lua\test\test.lua:12 in upvalue 'func2'
`
Path is the full path of tests file, while luajit for example emits only the filename.
Sidenote: This seems to have been fixed before but changes reverted at some point, #12 refers to a similar issue aswell.
> isatty fix for luvit runtime

- debugger.lua
message is optional and should default to "assertion failed!"
> fix trying to concat nil value on dbg.assert

- debugger.lua
For example, use `g0` to jump to the bottom of the stack.
Trying to jump out of range triggers cmd_trace instead.
> feat: add cmd_go

- debugger.lua
assume source input string, and load from C by `luaL_loadstring`:
```
---@type number
local a = 1
dbg()  -- break here and use `where`
a = a + 1
```
there are two problems:
1. the `info.currentline` would be `5`, while the `source`'s empty lines would be ignored, result to length `4`
2. the `---@type` 's `@` would be used as filename pattern, which was not right
both of these problems would results to `Error: Source not available for xxx`
> fix `where` source line parser when loaded from `luaL_loadstring`

- debugger.lua
when loaded by `luaL_loadstring`, the stacktrace is very hard to read, also, there's no generic ways to format it
so, it's better to let user to customize the format rules
also, the PR export `dbg.COLOR_GRAY` series, then users are able to customize colorful output
> allow user to customize format_loc and format_stack_frame_info

- debugger.lua
Lua's assert returns all provided arguments if there is no error - this change tries to match Lua's behavior.
Before this change, `local a, b, c = dbg.assert('a', 'b', 'c')` would make the values `a, b, c == 'a', 'assertion failed!', nil`.
> Forward all args from dbg.assert to lua_assert
